# Generated by Django 6.0.5 on 2026-05-28 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('camphub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='camphub.cohort'),
        ),
    ]
