# Generated by Django 6.0.5 on 2026-06-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
