# Generated by Django 6.0.5 on 2026-06-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccount_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='remind_bubble',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='remind_gym',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='remind_lessons',
            field=models.BooleanField(default=True),
        ),
    ]
