# Generated by Django 6.0.5 on 2026-06-19 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_personalreminder'),
        ('camphub', '0002_reminder_tvbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='remind_bubble',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='remind_gym',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='remind_lessons',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camphub.cohort'),
        ),
        migrations.DeleteModel(
            name='PersonalReminder',
        ),
    ]
