# Generated by Django 6.0.6 on 2026-07-14 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('sector', models.CharField(choices=[('MEDICAL', 'Medical'), ('FOOD', 'Food/Shop'), ('SECURITY', 'Security'), ('ADMIN', 'Administration'), ('TAXI', 'Taxi/Transport')], default='FOOD', max_length=20)),
                ('location', models.CharField(blank=True, choices=[('ON_CAMPUS', 'On Campus'), ('OFF_CAMPUS', 'Off Campus')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('GYM', 'Gym'), ('CLASS', 'Class'), ('BUBBLE', 'Bubble'), ('MEAL_TIME', 'Meal_Time')], default='GYM', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('ON_CAMPUS', 'on_campus'), ('OFF_CAMPUS', 'off_campus')], default='ON_CAMPUS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(choices=[('FESH', 'Fresh'), ('SOPH', 'Soph'), ('JUN', 'Jun'), ('SEN', 'Sen')], default='SOF', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MATH', 'Math'), ('ENGLISH', 'English'), ('PHYSICS', 'Physics'), ('KYRGIZ', 'Kyrgiz')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BubbleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_id', models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.event')),
            ],
        ),
        migrations.CreateModel(
            name='GymEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=50)),
                ('event_id', models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.event')),
            ],
        ),
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=50)),
                ('event_id', models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.event')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=15)),
                ('event_time_str', models.CharField(max_length=10)),
                ('reminder_offset', models.IntegerField()),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_name', models.CharField(choices=[('CM', 'CM'), ('CS', 'CS')], max_length=50)),
                ('study_year_id', models.ForeignKey(blank=True, db_column='study_year_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.studyyear')),
            ],
        ),
        migrations.CreateModel(
            name='ClassEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_id', models.ForeignKey(blank=True, db_column='cohort_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.cohort')),
                ('event_id', models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.event')),
                ('instructor_id', models.ForeignKey(blank=True, db_column='instructor_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.instructor')),
                ('room_id', models.ForeignKey(blank=True, db_column='room_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.room')),
                ('subject_id', models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TVBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lounge_name', models.CharField(max_length=50)),
                ('booker_name', models.CharField(max_length=100)),
                ('booking_date', models.CharField(max_length=10)),
                ('booking_time', models.CharField(max_length=5)),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
