# Generated by Django 6.0.5 on 2026-05-28 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MATH', 'Math'), ('ENGLISH', 'English'), ('CALCULUS', 'Calculus'), ('MALE', 'Male'), ('FEMALE', 'Female'), ('FACULTY', 'Faculty'), ('CLEANING', 'Cleaning'), ('CLEANING & DISINFECTION', 'Cleaning & Disinfection'), ('ALTAI-NARYN FOOTBALL SCHOOL', 'Altai-Naryn Football School'), ('JUDO GRAPPLING', 'Judo Grappling'), ('MCHS', 'MCHS'), ('PHYSICAL EDUCATION', 'Physical Education'), ('VOLLEYBALL', 'Volleyball')], default='MATH', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('sector', models.CharField(choices=[('MEDICAL', 'Medical'), ('FOOD', 'Food/Shop'), ('SECURITY', 'Security'), ('ADMIN', 'Administration')], max_length=20)),
                ('location', models.CharField(choices=[('ON_CAMPUS', 'On Campus'), ('OFF_CAMPUS', 'Off Campus')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('ON_CAMPUS', 'on_campus'), ('OFF_CAMPUS', 'off_campus')], default='ON_CAMPUS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='StudyYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduleentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('entry_type', models.CharField(blank=True, choices=[('LESSON', 'Lesson'), ('EXAM', 'Exam')], max_length=20, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.activity')),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.cohort')),
                ('instructors', models.ManyToManyField(blank=True, to='camphub.instructor')),
                ('rooms', models.ManyToManyField(blank=True, to='camphub.room')),
            ],
        ),
        migrations.CreateModel(
            name='Entryrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camphub.room')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camphub.scheduleentry')),
            ],
        ),
        migrations.AddField(
            model_name='cohort',
            name='study_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camphub.studyyear'),
        ),
    ]
