# Generated by Django 6.0.6 on 2026-06-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sector',
            field=models.CharField(blank=True, choices=[('MEDICAL', 'Medical'), ('FOOD', 'Food/Shop'), ('SECURITY', 'Security'), ('ADMIN', 'Administration')], max_length=20, null=True),
        ),
    ]
