# Generated by Django 6.0.6 on 2026-07-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyyear',
            name='year_name',
            field=models.CharField(choices=[('FESH', 'Fresh'), ('SOPH', 'Soph'), ('JUN', 'Jun'), ('SEN', 'Sen')], default='SOF', max_length=50),
        ),
    ]
