# Generated by Django 6.0.6 on 2026-06-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0002_alter_contact_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.CharField(blank=True, choices=[('ON_CAMPUS', 'On Campus'), ('OFF_CAMPUS', 'Off Campus')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sector',
            field=models.CharField(choices=[('MEDICAL', 'Medical'), ('FOOD', 'Food/Shop'), ('SECURITY', 'Security'), ('ADMIN', 'Administration')], default='ON_CAMPUS', max_length=20),
        ),
    ]
