# Generated by Django 6.0.5 on 2026-06-27 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0002_reminder_tvbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('GYM', 'Gym'), ('CLASS', 'Class'), ('BUBBLE', 'Bubble'), ('MEAL_TIME', 'Meal_Time')], default='GYM', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='cohort',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.room'),
        ),
        migrations.CreateModel(
            name='GymEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='camphub.event')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=50)),
            ],
            bases=('camphub.event',),
        ),
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='camphub.event')),
                ('meal_name', models.CharField(max_length=50)),
            ],
            bases=('camphub.event',),
        ),
        migrations.CreateModel(
            name='ClassEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='camphub.event')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camphub.cohort')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camphub.instructor')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camphub.subject')),
            ],
            bases=('camphub.event',),
        ),
    ]
