# Generated by Django 6.0.6 on 2026-07-10 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0002_alter_studyyear_year_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='room_id',
            field=models.OneToOneField(blank=True, db_column='room_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
