# Generated by Django 6.0.5 on 2026-06-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0002_reminder_tvbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entryrooms',
        ),
    ]
