# Generated by Django 6.0.5 on 2026-06-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0003_event_subject_rename_firstname_instructor_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='entryrooms',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='entryrooms',
            name='room',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='rooms',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Entryrooms',
        ),
        migrations.DeleteModel(
            name='Scheduleentry',
        ),
    ]
