# Generated by Django 6.0.6 on 2026-06-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0003_alter_contact_location_alter_contact_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sector',
            field=models.CharField(choices=[('MEDICAL', 'Medical'), ('FOOD', 'Food/Shop'), ('SECURITY', 'Security'), ('ADMIN', 'Administration')], default='FOOD', max_length=20),
        ),
    ]
