# Generated by Django 6.0.6 on 2026-07-10 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0003_alter_cohort_room_id_alter_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='classevent',
            name='room_id',
            field=models.ForeignKey(blank=True, db_column='room_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.room'),
        ),
    ]
