# Generated by Django 6.0.6 on 2026-06-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0004_alter_contact_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
