# Generated by Django 6.0.6 on 2026-07-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0004_classevent_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='room_id',
        ),
        migrations.AddConstraint(
            model_name='classevent',
            constraint=models.UniqueConstraint(fields=('cohort_id', 'event_id'), name='unique_cohort_time_slot'),
        ),
        migrations.AddConstraint(
            model_name='classevent',
            constraint=models.UniqueConstraint(fields=('room_id', 'event_id'), name='unique_room_time_slot'),
        ),
        migrations.AddConstraint(
            model_name='classevent',
            constraint=models.UniqueConstraint(fields=('instructor_id', 'event_id'), name='unique_instructor_time_slot'),
        ),
    ]
