# Generated by Django 6.0.6 on 2026-06-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0005_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sector',
            field=models.CharField(choices=[('MEDICAL', 'Medical'), ('FOOD', 'Food/Shop'), ('SECURITY', 'Security'), ('ADMIN', 'Administration'), ('TAXI', 'Taxi/Transport')], default='FOOD', max_length=20),
        ),
    ]
