# Generated by Django 6.0.6 on 2026-07-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0005_remove_cohort_room_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('MATH', 'Math'), ('ENGLISH', 'English'), ('PHYSICS', 'Physics'), ('KYRGIZ', 'Kyrgiz')], max_length=50),
        ),
    ]
