# Generated by Django 6.0.6 on 2026-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0006_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='cohort_name',
            field=models.CharField(choices=[('CM', 'CM'), ('CS', 'CS')], max_length=50),
        ),
    ]
