# Generated by Django 6.0.5 on 2026-07-07 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0006_alter_contact_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvbooking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='tvbooking',
            name='booking_time',
        ),
        migrations.AddField(
            model_name='reminder',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.event'),
        ),
        migrations.AddField(
            model_name='tvbooking',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.event'),
        ),
    ]
