# Generated by Django 6.0.6 on 2026-07-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0007_alter_cohort_cohort_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classevent',
            name='unique_cohort_time_slot',
        ),
        migrations.RemoveConstraint(
            model_name='classevent',
            name='unique_room_time_slot',
        ),
        migrations.RemoveConstraint(
            model_name='classevent',
            name='unique_instructor_time_slot',
        ),
    ]
