# Generated by Django 6.0.5 on 2026-07-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0007_remove_tvbooking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('GYM', 'Gym'), ('CLASS', 'Class'), ('BUBBLE', 'Bubble'), ('MEAL_TIME', 'Meal_Time'), ('TV', 'TV')], default='GYM', max_length=50),
        ),
    ]
