# Generated by Django 6.0.5 on 2026-07-07 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0008_event_date_alter_event_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classevent',
            name='cohort_id',
            field=models.ForeignKey(blank=True, db_column='cohort_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.cohort'),
        ),
        migrations.AlterField(
            model_name='classevent',
            name='event_id',
            field=models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.event'),
        ),
        migrations.AlterField(
            model_name='classevent',
            name='instructor_id',
            field=models.ForeignKey(blank=True, db_column='instructor_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.instructor'),
        ),
        migrations.AlterField(
            model_name='classevent',
            name='subject_id',
            field=models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.subject'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='room_id',
            field=models.ForeignKey(blank=True, db_column='room_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.room'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='study_year_id',
            field=models.ForeignKey(blank=True, db_column='study_year_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.studyyear'),
        ),
        migrations.AlterField(
            model_name='gymevent',
            name='event_id',
            field=models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.event'),
        ),
        migrations.AlterField(
            model_name='mealtime',
            name='event_id',
            field=models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.event'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='event_id',
            field=models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.event'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tvbooking',
            name='event_id',
            field=models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='camphub.event'),
        ),
        migrations.AlterField(
            model_name='tvbooking',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
