# Generated by Django 6.0.5 on 2026-07-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camphub', '0009_alter_classevent_cohort_id_alter_classevent_event_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='day',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_type',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='subject_name',
        ),
    ]
